image: node:22.14.0

before_script:
  - npm ci

create-pages:
  stage: build
  script:
    - export NEXT_PUBLIC_BASE_PATH="$(node -e "const url = process.env.CI_PAGES_URL; if (!url) process.exit(1); process.stdout.write(new URL(url).pathname.replace(/\\/$/, ''))")"
    - npm run build
  pages:
    publish: dist/client
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
